### ISSUE TITLE
nice 👍🏼

### ISSUE THREAD

**Issue by 0u44** [SirCryptic/script-dumping-ground#2]
imma look throughout these when i got the time

**Comment by SirCryptic** [comment]
@CPScript 
> imma look throughout these when i got the time

Thanks, just to let you know there is a discussions section [here](https://github.com/SirCryptic/script-dumping-ground/discussions) where you can leave feedback and input, I hope you enjoy looking through the repo please keep in mind that some of these scripts are very old that are from a hdd
